default_platform(:android)

platform :android do

    lane :default do
        internal
    end

    # LANE 1
    desc "Publish a new version to the Google Play (INTERNAL)"
    lane :internal do

        # Generate AAB file
        gradle(
            task: "demoscannerapp:bundle",
            build_type: "Release"
        )
    end
end
