default_platform(:android)

platform :android do

    lane :default do
        internal
    end

    # LANE 1
    desc "Publish a new version to the Google Play (INTERNAL)"
    lane :internal do

        # Generate AAB file
        gradle(
            task: "demoscannerapp:bundle",
            build_type: "Release"
        )

        # Upload the AAB to play store (internal track)
        upload_to_play_store(
            package_name: "com.enioka.scanner.demoscannerapp.release",
            track: 'internal',
            release_status: "draft",
            skip_upload_apk: true
        )
    end
end
