name: Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build the release package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: enioka_scan:assembleRelease
        env:
          SIGN_KEYID: ${{ secrets.SIGN_KEYID }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
      - name: Publish the library
        uses: gradle/gradle-build-action@v2
        with:
          arguments: enioka_scan:publish
        env:
          RUN_ID: ${{ github.run_id }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}