name: PlayStore release

on:
  push:
    branches:
      - playstore-cd

jobs:
  playstore:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.2"
          bundler-cache: true

      - name: Restore json key # make sure that you restore the key in the correct directory (ref. fastlane/Appfile)
        run: echo "${{ secrets.GOOGLE_API_PUB_JSON_BASE64 }}" | base64 --decode >  ${{ github.workspace }}/service-account.json

      - name: Restore keystore # make sure that you restore the key in the correct directory (same as app/gradle.properties)
        run: echo "${{ secrets.GOOGLE_KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/demoscannerapp/debug.keystore

      - name: Set up environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Fastlane build and upload
        run: bundle exec fastlane internal
        env:
          KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_KEYSTORE_PASSWORD }}
          SIGNKEY_PASSWORD: ${{ secrets.GOOGLE_SIGNKEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.GOOGLE_SIGNKEY_ALIAS }}

