name: Publish integration plugins to NPM

on:
  workflow_dispatch:

jobs:
  publish-reactnative-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./npm_integration_frameworks/reactnative/.nvmrc

      - name: Restore dependencies
        id: yarn-cache
        uses: actions/cache/restore@v4.2.3
        with:
          path: |
            ./npm_integration_frameworks/reactnative/**/node_modules
            ./npm_integration_frameworks/reactnative/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: ./npm_integration_frameworks/reactnative
        run: yarn install --immutable
        shell: bash

      - name: Cache dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4.2.3
        with:
          path: |
            ./npm_integration_frameworks/reactnative/**/node_modules
            ./npm_integration_frameworks/reactnative/.yarn/install-state.gz
          key: ${{ steps.yarn-cache.outputs.cache-primary-key }}

      - name: Publish to NPM
        working-directory: ./npm_integration_frameworks/reactnative
        run: yarn publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-cordova-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./npm_integration_frameworks/cordova-capacitor/.nvmrc

      - name: Publish to NPM
        working-directory: ./npm_integration_frameworks/cordova-capacitor
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
