name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Set up environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GH_DRIVER_REPOSITORY_USERNAME: ${{ secrets.GH_DRIVER_REPOSITORY_USERNAME }}
          GH_DRIVER_REPOSITORY_TOKEN: ${{ secrets.GH_DRIVER_REPOSITORY_TOKEN }}
      - name: Publish the library to MavenCentral
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          OSSRH_LOGIN: ${{ secrets.OSSRH_LOGIN }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGN_KEYID: ${{ secrets.SIGN_KEYID }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
          LIB_VERSION: ${{ steps.get_version.outputs.VERSION }}
          GH_DRIVER_REPOSITORY_USERNAME: ${{ secrets.GH_DRIVER_REPOSITORY_USERNAME }}
          GH_DRIVER_REPOSITORY_TOKEN: ${{ secrets.GH_DRIVER_REPOSITORY_TOKEN }}
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1 # No longer maintained
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: enioka_scan/build/outputs/aar/enioka_scan-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload AAR as GitHub release asset
        uses: actions/upload-release-asset@v1 # No longer maintained
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: enioka_scan/build/outputs/aar/enioka_scan-release.aar
          asset_name: enioka_scan-${{ steps.get_version.outputs.VERSION }}.aar
          asset_content_type: application/android-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}