name: Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build enioka_scan:test enioka_scan_mock:test